### PR TITLE
Merge from master

### PR DESCRIPTION
**Pull request by sum-coderepo**

### CODE REVIEW

**Comment by jeffheaton** [comment]
Thanks for these I will have a look soon.

**Comment by sum-coderepo** [comment]
Hi Jeff,

Sorry the pull request was raised by mistake. I am greatly helped by your
code and regularly updated my forked.

I have a query:-

Do you advice to use inbuilt method from sklearn or tensorflow in
production or go with TDD development and create custom functions in python?

Thanks and regards

**Comment by jeffheaton** [comment]
Okay, thanks, no problem.  For sklearn in production, I usually build it into a Python function that I can deploy as an AWS Lambda.  That is actually how the autochecker that I use in my class works.  As to TDD I try to automate as much of the AWS Lambda deploy as I can and have the usual sorts of unit tests built in before the function is deployed to AWS.

**Comment by jeffheaton** [comment]
No problem on the pull, I just closed it.

**Pull request closed without merging**
